### ISSUE TITLE
无法启动cluster.js

### ISSUE THREAD

**Issue by xiaoluzhi** [deepwn/deepMiner#39]
```
/srv/deepMiner/cluster.js:16
    console.log(`[!] Daemon start. PID: ${process.pid}\n`);
                ^
SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:945:3
```
nodejs版本
v0.10.48

**Comment by xiaoluzhi** [comment]
当我直接运行server.js时提示
``

/srv/deepMiner/server.js:54
const stats = (req, res) => {
                          ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:945:3
``

**Comment by evil7** [comment]
换到Latest版本（8.x）
或者去掉这个文件里，所有的 `console.log(........);`

**Comment by evil7** [comment]
低版本没有这const let 这类特性。换高版本，我 `install.sh` 脚本里有node的安装，单独拿出来也行。或者自己去官网下deb装吧

**Comment by xiaoluzhi** [comment]
nodejs的Latest好像无法运行node-cryptonote-pool

**Comment by evil7** [comment]
恩，我正在重写一个类似node-cryptonote-pool的项目，更轻量。你可以先用docker装pool

**Comment by xiaoluzhi** [comment]
好的，感谢~
