### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by vphelipe** [deepwn/deepMiner#9]
/srv/deepMiner/node_modules/ws/lib/WebSocket.js:344
      else throw new Error('not opened');
           ^

Error: not opened
    at WebSocket.send (/srv/deepMiner/node_modules/ws/lib/WebSocket.js:344:18)
    at pool2ws (/srv/deepMiner/server.js:142:13)
    at Socket.conn.pl.on (/srv/deepMiner/server.js:202:3)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)

**Comment by evil7** [comment]
I don't know what happen just from this Err report.
Some like your `websocket.js` lib wrong. Is that your server not start listening? Or iptable banned ports maybe.
Have U complete the `install.sh` steps? all config set done? maybe pool connect lost. check can the VPS ping to pool if it's right domain of pool.
